UPDATE "SupportRequest" SET status='PENDING' WHERE status IN ('NEED_SPARE','SPARE_ALLOCATED','PURCHASE_REQUESTED');
DELETE FROM "SpareRequest";
UPDATE "User" SET role='REQUESTER' WHERE role='APPROVER';
